# Generated by Django 5.2.1 on 2025-08-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_userprofile_options_userprofile_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(blank=True, help_text='Verification code for email change', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration time for email verification code', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, help_text='New email address pending verification', max_length=254, null=True),
        ),
    ]
