# Generated by Django 5.2.1 on 2025-08-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_expires',
        ),
    ]
